name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run feature summary check
        run: npm run gen:features:check

      - name: Install frontend deps
        run: npm ci --prefix packages/frontend

      - name: Build frontend
        run: npm run build --prefix packages/frontend
