name: Feature summary sync check

on:
  pull_request:
    paths:
      - 'docs/canva_adobe_express_feature_audit_detailed.json'
      - 'docs/canva_adobe_express_feature_audit.json'
  push:
    branches:
      - feature/agent-machine-orientation

jobs:
  check-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install (no deps)
        run: echo 'no install required'

      - name: Run summary check
        run: node scripts/generate-feature-summary.js --check
